import Head from 'next/head';
import Link from 'next/link';
import Layout from 'components/layout';
export default function Home() {
  const htmlComonentList = [
    { linkText: 'Editorial card', path: '/editorial-card' },
    { linkText: 'Blockquote', path: '/blockquote' },
  ];
  const reactComponentList = [];

  return (
    <div>
      <Head>
        <title>Component Workbench</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Layout>
          <section>
            <h1>Workbench</h1>
            <p>Have a look at our components</p>
          </section>

          <section>
            <nav>
              <ul>
                <li>
                  <Link href="/components/editorial-card">
                    <a>Editorial card</a>
                  </Link>
                </li>
              </ul>
            </nav>
          </section>
        </Layout>
      </main>
    </div>
  );
}
