name: Build the Workbench and deploy to development

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Use Node.js 16
      uses: actions/setup-node@v1
      with:
        node-version: 16.x

    - name: install workbench dependencies
      run: |
        cd workbench
        yarn install

    - name: build static output
      run: |
        cd workbench
        yarn run build:static

    - name: Install one-web-hosting-tool
      run: |
        curl https://static.coop.co.uk/one-web-hosting-tool/install.sh | sh

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.DEV_AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.DEV_AWS_SECRET_ACCESS_KEY }}
        role-to-assume: ${{ secrets.DEV_AWS_ROLE_ID }}
        aws-region: eu-west-1
        role-skip-session-tagging: true
        role-duration-seconds: 3600
      
    - name: Deploy to development 
      run: |
        one-web-hosting deploy --env=dev --yes