name: Version

on:
  # workflow_dispatch:
  push:
    branches: [master]

jobs:
  versioning:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "16.x"

      - name: Run install and lerna boostrap
        run: npm ci

      - name: Run build
        run: npm run build

      - name: Run lerna version
        run: npm run package:version
