name: Version

on:
  workflow_dispatch:

jobs:
  versioning:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14.x"

      - name: Run install and lerna boostrap
        run: npm ci

      - name: Run build
        run: npm run build

      - name: setup git
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "Github actor = $GITHUB_ACTOR"

      # - name: Set remote
      # env:
      #   GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      # run: |
      #   git config --global user.name 'github-actions[bot]'
      #   git config --global user.email 'github-actions[bot]@users.noreply.github.com'
      #   git remote set-url origin https://x-access-token:${GITHUB_TOKEN}@github.com/$GITHUB_REPOSITORY
      # - run: git remote add origin git@github.com:coopdigital/coop-frontend.git

      # - name: Lerna version
      # run: npm run package:version
