name: Version

on:
  workflow_dispatch:

jobs:
  versioning:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14.x"

      - name: install and boostrap
        run: npm ci

      - name: test and build
        run: npm run build

      - name: setup git
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "$GITHUB_ACTOR"
          git config user.email $GITHUB_ACTOR@users.noreply.github.com
          git config user.name $GITHUB_ACTOR

      - name: Lerna version
        run: npm run package:version
